name: deployment

on:
  push:
    branches:
      - 'master'

env:
  HEROKU_APP_NAME: nest-next-example-v1

jobs:
  build-and-push-image-to-heroku:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          cache-from: type=gha
          cache-to: type=gha

  deploy-to-heroku:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'goarvmn'
    needs: [build-and-push-image-to-heroku]
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      -
        name: Release image
        run: heroku container:release web -a ${{ env.HEROKU_APP_NAME }}